#!/bin/bash
UNAME_R=`uname -r`
UNAME_R_SUPPORTED='3.16.0-4-amd64'
if [ $UNAME_R != $UNAME_R_SUPPORTED ]
   then # Download and install a very specific set of prerequisites
        # that only are known to work for a very specific Linux install.
   echo "This script only supports Linux versions:"
   echo "    $UNAME_R_SUPPORTED"
   exit 1
fi

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

apachectl -k stop #in case webserver is running

if [ ! -f /usr/local/bin/perl ] #diysha needs /usr/local/bin/perl
        then # wasn't one, so link one in
                ln -s /usr/bin/perl /usr/local/bin/perl
fi
pushd diysha
git submodule update --init
cd HomeAutomation
make
cd w5xdInsteon/PowerLineModule
make install
cd ../bin
cp w5xdInsteon.so /usr/lib
cd ../../httpd/conf/private
echo "Generating a new private key for the web server"
openssl genrsa -out homeautomation.key 2048
chmod 600 homeautomation.key
cd ..
chmod 700 private
echo "Generating a new self-signed certificate for the web server"
openssl req -new -x509 -key private/homeautomation.key -out homeautomation.cert -days 3650 -batch \
   -subj "/O=DIYSHA Home Automation/CN=Need to run openssl req"
echo "We will now create one username and password for internet logins to this website"
echo "You will be able to create more later using command line tools"
read -p "Username for website login:" username
read -p "password for website login:" passwd
htpasswd -b htusers $username $passwd
popd

mkdir /var/diysha/HomeAutomation/httpd/htdocs/insteon
chown www-data /var/diysha/HomeAutomation/httpd/htdocs/insteon
mkdir /var/diysha/HomeAutomation/logs
chown www-data /var/diysha/HomeAutomation/logs

#www-data runs the webserver and must write a couple of things
chown www-data /var/diysha/HomeAutomation/httpd/logs /var/diysha/HomeAutomation/httpd/run /var/diysha/HomeAutomation/routerMonitor /var/diysha/HomeAutomation/thermostat /var/diysha/HomeAutomation/hvac
cp -r diysha/turnkeylinux/etc/apache2 /etc
cp diysha/turnkeylinux/etc/init.d/* /etc/init.d/
a2enmod cgid
a2enmod ssl
a2enmod perl
a2enmod proxy
a2enmod xml2enc
a2enmod proxy_http
pushd /etc
ln -s ../init.d/HomeAutomation rc2.d/S02HomeAutomation
ln -s ../init.d/HomeAutomation rc3.d/S02HomeAutomation
ln -s ../init.d/HomeAutomation rc5.d/S02HomeAutomation
cd apache2
echo "export HTTPD_LOCAL_ROOT=/var/diysha/HomeAutomation/httpd" >> envvars
cd sites-enabled
ln -s ../sites-available/homeautomation-ssl.conf
rm 000-default.conf
cd ../conf-enabled
ln -s ../conf-available/homeautomation* .
rm security.conf
rm serve-cgi-bin.conf
popd

# The time zone must match that of the radiothermostat
echo "The time zone setting for this Linux must"
echo "match that of the wifi radiothermostat to make times match. Any key to continue"
read
dpkg-reconfigure tzdata
update-rc.d apache2 enable #enable on boot

echo "Force reboot"
shutdown -r now

