#!/bin/sh
#Copyright (c) 2013 by Wayne Wright, Round Rock, Texas.
#See license at http://github.com/w5xd/diysha/blob/master/LICENSE.md 
echo "Content-type: text/plain; charset=iso-8859-1"
echo
tail -n 200 ../../hvac/relay_events.log
