#!/usr/local/bin/perl
#Copyright (c) 2017 by Wayne Wright, Round Rock, Texas.
#See license at http://github.com/w5xd/diysha/blob/master/LICENSE.md 
use lib "../..";
require define_local;

define_local::SetEnvironmentVariables("../../HouseConfiguration.ini");

print STDOUT <<Begin_of_output_STDOUT;
Content-type: text/plain; charset=iso-8859-1

Begin_of_output_STDOUT
system ('tail -n 200 '. $ENV{'THERMOSTAT_LOG_LOCATION'} . '/thermostat_log.txt');
