#!/bin/bash
#helper to be first to read this website after a system boot.

background () {
let CUR=1
while [ $CUR -gt 0 ]; do
 sleep 10  #Give startup a chance to complete
 curl localhost/HomeAutomationStart
 sleep 1h
done
}

background &
