#!/bin/bash
if [ ! -d "$THERMOSTAT_LOG_LOCATION" ]; then
    mkdir "$THERMOSTAT_LOG_LOCATION"
fi
LOGFILEOUT=$THERMOSTAT_LOG_LOCATION/"thermostat_log.txt"

#process old logs in root of thermostat log dir
./processEventLog $THERMOSTAT_LOG_LOCATION $LOGFILEOUT

SUBDIR=`date +"%Y_%m_%d_%H%M%S"`
SUBDIR=$THERMOSTAT_LOG_LOCATION/"logs_"$SUBDIR
mkdir $SUBDIR
let CURLOG=1
while [ $CURLOG -gt 0 ]; do
    LOGPATH=$SUBDIR/log$CURLOG
    curl --max-time 60 http://$THERMOSTAT_IP/tstat/eventlog > $LOGPATH
    ./processEventLog -a $LOGPATH $LOGFILEOUT
    RES=$?
#    if [ $RES -ge 45 ] && [ $RES -le 90 ] ; then
#        if [ $RES -ge 58 ] ; then
#            curl -d '{"tmode":1,"t_heat":57}' http://$THERMOSTAT_IP/tstat
#            echo "Lowering setting to 57"
#        elif [ $RES -le 56 ] ; then
#            curl -d '{"tmode":1,"t_heat":59}' http://$THERMOSTAT_IP/tstat
#            echo "Raising setting to 58"
#            sleep 60s
#            curl -d '{"tmode":1,"t_heat":57}' http://$THERMOSTAT_IP/tstat
#            echo "Lowering setting to 57"
#       fi
#    fi
    sleep 30m
    let CURLOG=CURLOG+1
done
# https://github.com/ThermoMan/Thermostat-Tracking/blob/master/lib/t_lib.php for other API example
