#!/bin/bash
#Combines the various temperature sensors in a single stdout
if [ $# -lt 1 ] ; then
   echo "URL plus (optional) login parameters for curl needed" 1>&2
   exit 1;
fi

echo '*** furnace.cgi ***'
curl --silent --max-time 30 $2 http://$1/furnace.cgi
RES=$?
if [ $RES -ne 0 ] ; then
    date 1>&2
    echo "curl furnace.cgi failed $RES" 1>&2
fi
