#!/usr/local/bin/perl -w -I..

# perl program to call the forecast.weather.gov for lat/lon URL at first arg

use strict;
use hvac::WeatherGov;

my $url = shift;    # URL is first argument to this script

my $obj = hvac::WeatherGov->new($url);
$obj->acquireTemperature();
$obj->printWeatherGov();
1;
