#!/bin/bash

#must have defined $FURNACE_IP and $FURNACE_LOGIN and $FURNACE_LOG_LOCATION
./poll_events $FURNACE_LOG_LOCATION/poll_events.log $FURNACE_LOG_LOCATION/relay_events.log 2>$FURNACE_LOG_LOCATION/poll_events_err.txt &
P2=$!
echo "hvac monitor Started $P2"
echo -e "#!/bin/bash\n\
	cwd `pwd`\n\
	kill $P2\n\
	export FURNACE_IP='$FURNACE_IP'\n\
        export FURNACE_LOGIN='$FURNACE_LOGIN'\n\
	export FURNACE_LOG_LOCATION='$FURNACE_LOG_LOCATION'"\
       	> $FURNACE_LOG_LOCATION/stop_last_monitor.sh
