#!/bin/bash

#must have defined $FURNACE_IP and $FURNACE_LOGIN
./poll_events poll_events.log relay_events.log 2>poll_events_err.txt &
P2=$!
echo "Started $P2"
echo -e "#!/bin/bash\nkill $P2\n\
	export FURNACE_IP='$FURNACE_IP'\nexport FURNACE_LOGIN='$FURNACE_LOGIN'"\
       	> stop_last_monitor
chmod +x stop_last_monitor
