#!/bin/bash
#Loop forever calling the combine_inputs script.
#set up various stderr log files in the process current directory
#
#the heat pump mininum temperature is the required first argument
#the url for the local weather observation temperature is the required second arg
#

NOT USED ANYMORE

if [ $# -lt 2 ]
then
	echo "poll_furnace requires a heat-pump temperature command line argument, and URL for local weather" 1>&2
	exit 2
fi
#will append to the error output files, so remove them
rm -f combine_inputs_err.txt procFurnace_err.txt check_set_eheat_out.txt
COUNTER=0
while [ $COUNTER -lt 1 ] ; do
   LINEOUT=`./combine_inputs "$2" 2>>combine_inputs_err.txt | ./procFurnace 2>>procFurnace_err.txt`
   #pass the results of the poll to check_set_heat as command args (redirecting all its output to a file)
   if [ -n "$LINEOUT" ]
   then
      ./check_set_eheat $1 $LINEOUT >> check_set_eheat_out.txt 2>&1
      #and also send this polling result to our own stdout
      echo $LINEOUT 
      sleep 3m
   else 
      sleep 30s
   fi
   #run forever, acquiring temperatures every 5m
   #let COUNTER=COUNTER+1
done
