#!/usr/local/bin/perl
#
#started from /etc/init.d/HomeAutomation
#
use strict;
use warnings;

use File::Basename;
use File::Spec;
use File::Path qw(make_path);

# setup software install location
my ($fn, $DIR) = fileparse($0);  #base file specs on location of this script
	($fn, $DIR) = fileparse(substr($DIR,0,-1));
        $DIR = substr($DIR, 0, -1); 
        $DIR = File::Spec->rel2abs($DIR);

	require $DIR . '/define_local.pm';

	# setup hardware configuration dependencies
	define_local::SetEnvironmentVariables( $DIR . '/HouseConfiguration.ini');

	#thermostat and hvac logs need a home. 
	if (! -d $ENV{'THERMOSTAT_LOG_LOCATION'}) {
		make_path($ENV{'THERMOSTAT_LOG_LOCATION'});
	}
	if (! -d $ENV{'FURNACE_LOG_LOCATION'}) {
		make_path($ENV{'FURNACE_LOG_LOCATION'});
	}

	if (-e "$DIR/../motion/startMotion") { #motion directory does not appear on Windows...
		chdir "$DIR/../motion";
		system('./startMotion >motion.log 2>&1 &');
	}
	
	chdir "$DIR/routerMonitor";
	system ('bash monitor >>' . $ENV{'THERMOSTAT_LOG_LOCATION'} . '/monitor.log 2>&1  &');

	chdir "$DIR/thermostat";
	system ('bash monitorThermostat >' .  $ENV{'THERMOSTAT_LOG_LOCATION'} . '/monitorThermostat.log 2>&1 &');

#	chdir  "$DIR/hvac";
#	system ('bash -c ./monitor');


