#!/usr/local/bin/perl
#
#started from /etc/init.d/HomeAutomation
#
use strict;
use warnings;

use File::Basename;
use File::Spec;

# setup software install location
my ($fn, $DIR) = fileparse($0);  #base file specs on location of this script
	($fn, $DIR) = fileparse(substr($DIR,0,-1));
        $DIR = substr($DIR, 0, -1); 
        $DIR = File::Spec->rel2abs($DIR);

	require $DIR . '/define_local.pm';

	# setup hardware configuration dependencies
	define_local::SetEnvironmentVariables( $DIR . '/HouseConfiguration.ini');

	#thermostat and hvac logs need a home. 
	if (! -d "$DIR/logs") {
		mkdir "$DIR/logs";
	}

	if (-e "$DIR/../motion") { #motion directory does not appear on Windows...
		chdir "$DIR/../motion";
		system('motion -c motion.conf >motion.log 2>&1 &');
	}
	
	chdir "$DIR/routerMonitor";
	system ('bash monitor >>monitor.log 2>&1  &');

	chdir "$DIR/thermostat";
	system ('bash monitorThermostat >monitorThermostat.log 2>&1 &');

#	chdir  "$DIR/hvac";
#	system ('bash -c ./monitor');


